### ISSUE TITLE
Unclear usage of next(err)

### ISSUE THREAD

**Issue by rohitsud** [restify/errors#82]
Documentation isn't clear when to use `return next(err);` vs using just `next(err);` For instance, everywhere it uses `return` except in the section `Checking Error types`

**Comment by benjcallaghan** [comment]
Calling `next(err);` is enough to send an error response that is properly serialized. Using `return next(err);` does the same, but also explicitly ends the current function. The `next` method doesn't return anything, so the calling function doesn't actually return anything either. It's just a convention to exit the function. This is most useful if the error occurs before the request handler has completed all processing. Consider the following example:

```javascript
function myRequestHandler(req, res, next) {
    if (!req.is('application/json')) {
        var err = new errors.BadRequestError();
        return next(err);
    }

    var result = doProcessing(req);
    res.json(result);
    return next();
}
```

If the request is not 'application/json', then the handler should abort and respond with an error. Otherwise, processing should occur, and the result should be returned in JSON format. If the keyword `return` had been left off on line 4, processing still would have occurred, even if the request was not 'application/json'. The `return` on line 9 is redundant since that's already the last line of the function.

My personal convention is to use `return next();` in every situation. I find it more readable, and it conveys quite clearly that the request handler has finished. I hope this helps.
